server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql://10.2.14.249:33406/zdb_bm
    username: root
    password: root@!^*
    driver-class-name: com.mysql.cj.jdbc.Driver


test:
  name: yaml_value